export const c = {
    shoppingCart: {
        en: "SHOPPING CART",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    emptyCart: {
        en: "Your cart is empty",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    goBack: {
        en: "Go Back",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    checkoutNow: {
        en: "CHECKOUT NOW",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    subTotal: {
        en: "SUBTOTAL",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    items: {
        en: "ITEMS",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    total: {
        en: "TOTAL",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    proceed: {
        en: "PROCEED TO CHECKOUT",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
};
