export const nav = {
    men: {
        en: "MEN",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    women: {
        en: "WOMEN",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    kid: {
        en: "KIDS",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    sale: {
        en: "SALE",
        cn: "SALE",
        jpn: "SALE",
        // de: "",
        // fr: "",
    },
    new: {
        en: "NEW ARRIVALS",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    cart: {
        en: "Cart",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    profile: {
        en: "Profile",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    yourorder: {
        en: "Your Orders",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    logout: {
        en: "Logout",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    signin: {
        en: "Sign In",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    user: {
        en: "Users",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    product: {
        en: "Products",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    order: {
        en: "Orders",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
};
