export const summary = {
    title: {
        en: "Order Summary",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    shipping: {
        en: "SHIPPING",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    payment: {
        en: "Payment Method",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    method: {
        en: "Method",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    address: {
        en: "Address",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    orderItems: {
        en: "Order Items",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    size: {
        en: "Size",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    color: {
        en: "Color",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    price: {
        en: "Price",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    items: {
        en: "ITEMS",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    shippingFee: {
        en: "Shipping Fee",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    tax: {
        en: "Tax",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    total: {
        en: "Total",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    pay: {
        en: "Proceed to Payment",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
};
