export const p = {
    price: {
        en: "Price",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    status: {
        en: "Status",
        cn: "Status",
        jpn: "Status",
        // de: "",
        // fr: "",
    },
    quantity: {
        en: "Quantity",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    size: {
        en: "Selected Size",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    color: {
        en: "Selected Color",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    sizeGuide: {
        en: "See Size Chart",
        cn: "",
        jpn:"",
        // de: "",
        // fr: "",
    },
    deliverNReturn: {
        en: "Deliver and Return",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",

    },
    addToCart: {
        en: "ADD TO CART",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    goBack: {
        en: "Go Back",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    payment: {
        en: "Acceptable Payment Methods",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
};
