export const shippingTranslate = {
    title: {
        en: "SHIPPING",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    givenName: {
        en: "Given Name",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    surname: {
        en: "Surname",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    email: {
        en: "Email Address",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    addressLine1: {
        en: "Address Line 1",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    addressLine2: {
        en: "Address Line 2",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    country: {
        en: "Country or Region",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    city: {
        en: "City",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    contact: {
        en: "Contact Number",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
    continue: {
        en: "Continue",
        cn: "",
        jpn: "",
        // de: "",
        // fr: "",
    },
};
